package Interfaces_Graficas;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class Interface_Consultas extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Interface_Consultas() {
    	super("Consultas");
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setText("Cliente que Fez a Viagem Mais Longa");
        jButton1.setToolTipText("Consulta Dylan");
        jButton1.addActionListener(
				new ActionListener()
				{
					public void actionPerformed(ActionEvent e)
					{
						new Visualizacoes('y');
					}
				});

        jButton2.setText("Todos Clientes Actualmente em Uma Viagem");
        jButton2.setToolTipText("Consulta Gilberto");
        jButton2.addActionListener(
				new ActionListener()
				{
					public void actionPerformed(ActionEvent e)
					{
						new Visualizacoes('g');
					}
				});

        jButton3.setText("Quantidade de Clientes que Estiveram em Cada Cidade");
        jButton3.setToolTipText("Consulta Lindsay");
        jButton3.addActionListener(
				new ActionListener()
				{
					public void actionPerformed(ActionEvent e)
					{
						new Visualizacoes('l');
					}
				});

        jButton6.setText("Cliente que Pagou o Valor Mais Alto");
        jButton6.setToolTipText("Consulta Eugenio");
        jButton6.addActionListener(
				new ActionListener()
				{
					public void actionPerformed(ActionEvent e)
					{
						new Visualizacoes('e');
					}
				});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6)
                    .addComponent(jButton3)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton6)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    // End of variables declaration                   
}
